PREFIX schema: <https://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX unit: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select * where { 
	?s schema:additionalType "power"  .
    ?s schema:geo ?geo .        
        
    ?geo geo:asWKT ?buildingLocation .
    
    BIND("POINT(-84.3555 41.3175)"^^geo:wktLiteral AS ?centroid)
    BIND(geof:buffer(?centroid, 8.04672, unit:kilometer) AS ?searchArea)
} 

